In [32]:
import numpy as np
import random as rand
import itertools

In [33]:
#set dimension
dim = 4
#generate random symmetric matrix
shp = np.random.randint(0, 20, size=(dim, dim), dtype='int')
shp = (shp + np.transpose(shp))/2
print(shp)
#get some dead rows
n = 3
all_rows = range(len(shp))
rand.shuffle(all_rows)
dead_rows = all_rows[:n]
print(dead_rows)
#get pairs of dead rows
dead_pairs = itertools.combinations(dead_rows, 2)

[[ 6 13 17  9]
 [13  5 18  9]
 [17 18  3  9]
 [ 9  9  9  0]]
[0, 2, 1]


In [35]:
np.fromiter(dead_pairs, dtype=bool)

array([ True,  True,  True], dtype=bool)

In [26]:
np.fromiter(dead_rows, bool)

array([ True, False,  True], dtype=bool)